table crimes
	lineageTag: 1f592234-78eb-40cd-9eae-fd4a378356e5

	measure 'Total Crimes' = SUM(crimes[Number of crimes])
		formatString: #,0
		lineageTag: f82e4049-255f-4b48-b1b3-92b8b9ad0a4a

	measure 'Avg per Month' = DIVIDE([Total Crimes], DISTINCTCOUNT(crimes[Month]))
		formatString: #,0
		lineageTag: fbe0933b-c146-4fcf-a506-407bb93f9eab

	column Borough
		dataType: string
		lineageTag: 6d3c3ee4-519c-4de5-bfbe-f4f74fc3a7af
		summarizeBy: none
		sourceColumn: Borough

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 168dd18f-18b2-4f78-9b71-ab8bc27c9f92
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Crime type'
		dataType: string
		lineageTag: ea72a223-153b-4eff-9979-8daf8fd5e5c1
		summarizeBy: none
		sourceColumn: Crime type

		annotation SummarizationSetBy = Automatic

	column 'Number of crimes'
		dataType: int64
		formatString: 0
		lineageTag: 15fcd428-06b4-4435-8cf4-27994d1937c7
		summarizeBy: sum
		sourceColumn: Number of crimes

		annotation SummarizationSetBy = Automatic

	column Year = YEAR(crimes[Month])
		formatString: 0
		lineageTag: 77ad224b-03fc-46b9-8ee7-e56c499aa233
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column MonthNum = MONTH(crimes[Month])
		formatString: 0
		lineageTag: e94b818d-d415-4ef7-ad88-c1b583eef9df
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column MonthName = FORMAT(crimes[Month], "MMM")
		lineageTag: 6430cbbe-ec1b-42dc-8e5f-99f29abd38d0
		summarizeBy: none
		sortByColumn: MonthNum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition crimes = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\datph\Desktop\DataAnalyst1stProject\data\processed\monthly_crimes_by_type_borough.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Borough", type text}, {"Month", type date}, {"Crime type", type text}, {"Number of crimes", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

